### ISSUE TITLE
MoEInAppHelper class not available in 12.2.03 (Android)

### ISSUE THREAD

**Issue by rohitAndroidC** [moengage/Android-Sample#10]
Can you please update the example code base to support the latest version of moengage sdk.

1) MoEInAppHelper was required to set callbacks class and for displaying in app using MoEInAppHelper.getInstance().showInApp(mContext) what is the alternative method for this.
2) For handling Push notification we had a straight forward method of "onHandleRedirection", but after update we are using onNotificationClick.
3) Alternative for "MoEngage.isAppForeground()" in the updated sdk ?

**Comment by rohitAndroidC** [comment]
Any update ?

**Comment by donynuransyah** [comment]
waiting for the update as well

**Comment by abirajabi** [comment]
any update on this issue? I'm using sdk 12.8.00 and faicing the same problem ...

**Comment by arshiya-moengage** [comment]
Please reach out to `support@moengage.com`.
