### ISSUE TITLE
How to connect with MoEngage Live Environment

### ISSUE THREAD

**Issue by rodrigocoliveira** [moengage/Android-Sample#2]
Hello, 

I have been trying to connect MoEngage with Segment. I could see my logs in the MoEngage dashboard (latest events) but they always go to the TEST environment. 

I would like to send it over LIVE environment, even when I am running the app on my local machine.

This is my source code:
```
// Segment Initialization
    Analytics analytics = new Analytics.Builder(this, BuildConfig.SEGMENT_WRITE_KEY)
                .use(MoEngageIntegration.FACTORY)
                .build();
    Analytics.setSingletonInstance(analytics);

// MoEngage Initialisation
    MoEngage moEngage = new MoEngage.Builder(this,  BuildConfig.MOENGAGE_APP_ID)
                .enableSegmentIntegration()
                .build();
    MoEngage.initialise(moEngage);
```

So I am currently creating an Analytics Object for the segment SDK and enabling the segment integration to the MoEngage SDK.

With that said: How can I initialise the MoEngage SDK to the Live environment, something similar to the **initializeProdWithAppID** on the iOS SDK ?

@umangmoe

**Comment by umangmoe** [comment]
@rodrigocoliveira This FAQ should answer your question - https://docs.moengage.com/docs/troubleshooting-1#q-cannot-see-data-on-the-dashboard

Request you to reach out to us via our support email `support@moengage.com` for faster solutions.

**Comment by umangmoe** [comment]
I hope this is resolved. Closing this please re-open if required.
